spring.application.name=InsurancePolicyManagement

spring.datasource.url=jdbc:mysql://localhost:3306/insurance_db?createIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
